### ISSUE TITLE
Install smart-check.py in $PATH [feature]

### ISSUE THREAD

**Issue by petski** [ercpe/smart-check#2]
Hi,

`setup.py build install` doesn't seem to create a convenient binary in `$PATH`. As a work-around I'm doing this:

```
git clone https://github.com/ercpe/smart-check
cd smart-check
python setup.py build install
ln -s /usr/lib/python2.7/site-packages/smart_check-0.3-py2.7.egg/smartcheck/main.py /usr/bin/smartcheck.py
```

**Comment by ercpe** [comment]
Fixed in 0.3.1. Thank you for reporting.

**Comment by petski** [comment]
The shebang of `/usr/bin/smart-check` is incorrect if you'd ask me. Now only `python /usr/bin/smart-check <args>` works , but `/usr/bin/smart-check <args>` doesn't.

```
$ head -n1 /usr/bin/smart-check 
#!.
$ smart-check /dev/sdb
-bash: /usr/bin/smart-check: .: bad interpreter: Permission denied
```

**Comment by ercpe** [comment]
How did you install smart-check 0.3.1?  setuptools should replace the shebang with the current interpreter binary. I have just tested it on CentOS 7 and it works as expected.

**Comment by petski** [comment]
Hmmm, seems to be an issue with py-setuptools. I fixed it with this patch:

```
 rm -rf /root/smart-check*
 wget -q -O /root/smart-check.tar.gz https://github.com/ercpe/smart-check/archive/0.3.1.tar.gz
 tar -C /root/ -zxvf /root/smart-check.tar.gz
-(cd /root/smart-check-0.3.1/ && python setup.py build install)
+(cd /root/smart-check-0.3.1/ && /usr/bin/python setup.py build install)
 rm -rf /root/smart-check*
 chmod +s /usr/sbin/smartctl
```

Sorry for bothering

(FYI, I'm using your excellent tool in addition with [foreman-discovery-image](https://github.com/theforeman/foreman-discovery-image); in my case also based on CentOS 7)
