### ISSUE TITLE
False positive (when disk is in the device database?)

### ISSUE THREAD

**Issue by petski** [ercpe/smart-check#3]
Reallocated_Sector_Ct=0, but still a "CRITITAL" message is shown:

```
# python /usr/bin/smart-check --verbose --debug /dev/sda
DEBUG    Executing smartctl command:  /usr/sbin/smartctl  -n standby -a /dev/sda
... snip ...
DEBUG    Attribute 5 (Reallocated_Sector_Ct): value=100, raw value=0
... snip ...
DEBUG    Failed generic attributes: {}
DEBUG    Device exists in database (one of ['Seagate Constellation ES.3 SATAIII 4TB Serie', 'ST4000NM0033-9ZM170'] matches ST4000NM0033-9ZM170)
DEBUG    Device exists in database (one of ['Seagate Constellation ES.3 SATAIII 4TB Serie', 'ST4000NM0033-9ZM170'] matches ST4000NM0033-9ZM170)
INFO     Attribute 5 (Reallocated_Sector_Ct) failed: not 20 <= 0 <= 40
ST4000NM0033-9ZM170: CRITICAL: Reallocated_Sector_Ct=0
```

Smartctl output: [ST4000NM0033-9ZM170.txt](https://github.com/ercpe/smart-check/files/561679/ST4000NM0033-9ZM170.txt)

**Comment by ercpe** [comment]
Yes, the disks.yml contained wrong data for the Re-allocated sector count attribute for several disks. I will release a fixed version shortly.

If you suspect problems with the disks file, you can just use `--disks-file /dev/null` to only analyze the generic attributes.

**Comment by ercpe** [comment]
Fixed in 0.3.2.

**Comment by petski** [comment]
Thanks! I'll monitor this repo to see once 0.3.2 is released.... And it's already there. You're quick! :)

(Just thinking out loud: maybe it's nice to have the "generic"/"default" thresholds in disks.yaml as wel, under "_default" or something like that)

**Comment by ercpe** [comment]
Done in 0.4 (last release for today :) ).

The generic rules are now configured in https://github.com/ercpe/smart-check/blob/master/smartcheck/generic.yaml.  If an attribute isn't listed in the generic.yaml file (and the disk does not exist in disks.yaml either), the code still checks the value against the threshold.
