### ISSUE TITLE
Issue with --ignore-attributes

### ISSUE THREAD

**Issue by SanderDelden** [ercpe/smart-check#4]
Hi,

We're facing some issuess with smart-check when trying to ignore certain attributes.
When running the following command:
`smart-check /dev/sdf --verbose --ignore-attributes Temperature_Celcius --notices-are-warnings --smartctl-args ''`

We still get the following output:
`KINGSTON SUV400S37120G: NOTICE: Reallocated_Sector_Ct=2: The drive has a non-zero Raw value, but there is no SMART warning yet. This could be an indication of future failures and/or potential data loss in bad sectors., NOTICE: Temperature_Celsius=100: The temperature of the drive is higher than 50 degrees Celsius. This may shorten its lifespan and cause damage under severe load.; 1 ATA errors found`

As you can see the output still contains notices / warnings regarding the drive temperature. Instead of "Temperature_Celsius" we also tried the corresponding ID: 194 with no luck.

Attached is a file with the output from: `smartctl -A /dev/sdf`

[smartctl.txt](https://github.com/ercpe/smart-check/files/1971675/smartctl.txt)

**Comment by ercpe** [comment]
The command line argument of `--ignore-attributes` wasn't passed along. As a result, no attribute could ever be ignored. Version 0.4.2 fixes that - values for `--ignore-attributes` can either be the number or the name of the attribute.

Please note that you have a typo in the attribute name (it's Cel**s**ius).
